// Auto-generated by havamal's sync_to_blog.py. Do not edit by
// hand — edits will be clobbered on the next sync.

import type { ImageMetadata } from "astro";

import _f1EnDL from "./01-sixteen-kb-timing.en.light.png";
import _f1EnDD from "./01-sixteen-kb-timing.en.dark.png";
import _f1RuDL from "./01-sixteen-kb-timing.ru.light.png";
import _f1RuDD from "./01-sixteen-kb-timing.ru.dark.png";

import _f2EnDL from "./02-verdict-decision-flow.en.light.png";
import _f2EnDD from "./02-verdict-decision-flow.en.dark.png";
import _f2RuDL from "./02-verdict-decision-flow.ru.light.png";
import _f2RuDD from "./02-verdict-decision-flow.ru.dark.png";

import _f3EnDL from "./04-policy-state-machine.en.light.png";
import _f3EnDD from "./04-policy-state-machine.en.dark.png";
import _f3RuDL from "./04-policy-state-machine.ru.light.png";
import _f3RuDD from "./04-policy-state-machine.ru.dark.png";

import _f4EnDL from "./03-layer-map.en.light.png";
import _f4EnDD from "./03-layer-map.en.dark.png";
import _f4RuDL from "./03-layer-map.ru.light.png";
import _f4RuDD from "./03-layer-map.ru.dark.png";

export interface FigureVariants {
  desktopLight: ImageMetadata;
  desktopDark: ImageMetadata;
  mobileLight?: ImageMetadata;
  mobileDark?: ImageMetadata;
}

export type FigureSet = Record<"en" | "ru", FigureVariants>;

export const figures: Record<string, FigureSet> = {
  "01-sixteen-kb-timing": {
    en: { desktopLight: _f1EnDL, desktopDark: _f1EnDD },
    ru: { desktopLight: _f1RuDL, desktopDark: _f1RuDD },
  },
  "02-verdict-decision-flow": {
    en: { desktopLight: _f2EnDL, desktopDark: _f2EnDD },
    ru: { desktopLight: _f2RuDL, desktopDark: _f2RuDD },
  },
  "04-policy-state-machine": {
    en: { desktopLight: _f3EnDL, desktopDark: _f3EnDD },
    ru: { desktopLight: _f3RuDL, desktopDark: _f3RuDD },
  },
  "03-layer-map": {
    en: { desktopLight: _f4EnDL, desktopDark: _f4EnDD },
    ru: { desktopLight: _f4RuDL, desktopDark: _f4RuDD },
  },
};
