// Auto-generated by havamal's sync_to_blog.py. Do not edit by
// hand — edits will be clobbered on the next sync.

import type { ImageMetadata } from "astro";

import _f1EnDL from "./01-sixteen-kb-timing.en.light.png";
import _f1EnDD from "./01-sixteen-kb-timing.en.dark.png";
import _f1EnML from "./01-sixteen-kb-timing.mobile.en.light.png";
import _f1EnMD from "./01-sixteen-kb-timing.mobile.en.dark.png";
import _f1RuDL from "./01-sixteen-kb-timing.ru.light.png";
import _f1RuDD from "./01-sixteen-kb-timing.ru.dark.png";
import _f1RuML from "./01-sixteen-kb-timing.mobile.ru.light.png";
import _f1RuMD from "./01-sixteen-kb-timing.mobile.ru.dark.png";

import _f2EnDL from "./02-verdict-decision-flow.en.light.png";
import _f2EnDD from "./02-verdict-decision-flow.en.dark.png";
import _f2EnML from "./02-verdict-decision-flow.mobile.en.light.png";
import _f2EnMD from "./02-verdict-decision-flow.mobile.en.dark.png";
import _f2RuDL from "./02-verdict-decision-flow.ru.light.png";
import _f2RuDD from "./02-verdict-decision-flow.ru.dark.png";
import _f2RuML from "./02-verdict-decision-flow.mobile.ru.light.png";
import _f2RuMD from "./02-verdict-decision-flow.mobile.ru.dark.png";

import _f3EnDL from "./04-policy-state-machine.en.light.png";
import _f3EnDD from "./04-policy-state-machine.en.dark.png";
import _f3EnML from "./04-policy-state-machine.mobile.en.light.png";
import _f3EnMD from "./04-policy-state-machine.mobile.en.dark.png";
import _f3RuDL from "./04-policy-state-machine.ru.light.png";
import _f3RuDD from "./04-policy-state-machine.ru.dark.png";
import _f3RuML from "./04-policy-state-machine.mobile.ru.light.png";
import _f3RuMD from "./04-policy-state-machine.mobile.ru.dark.png";

import _f4EnDL from "./03-layer-map.en.light.png";
import _f4EnDD from "./03-layer-map.en.dark.png";
import _f4EnML from "./03-layer-map.mobile.en.light.png";
import _f4EnMD from "./03-layer-map.mobile.en.dark.png";
import _f4RuDL from "./03-layer-map.ru.light.png";
import _f4RuDD from "./03-layer-map.ru.dark.png";
import _f4RuML from "./03-layer-map.mobile.ru.light.png";
import _f4RuMD from "./03-layer-map.mobile.ru.dark.png";

export interface FigureVariants {
  desktopLight: ImageMetadata;
  desktopDark: ImageMetadata;
  mobileLight: ImageMetadata;
  mobileDark: ImageMetadata;
}

export type FigureSet = Record<"en" | "ru", FigureVariants>;

export const figures: Record<string, FigureSet> = {
  "01-sixteen-kb-timing": {
    en: { desktopLight: _f1EnDL, desktopDark: _f1EnDD, mobileLight: _f1EnML, mobileDark: _f1EnMD },
    ru: { desktopLight: _f1RuDL, desktopDark: _f1RuDD, mobileLight: _f1RuML, mobileDark: _f1RuMD },
  },
  "02-verdict-decision-flow": {
    en: { desktopLight: _f2EnDL, desktopDark: _f2EnDD, mobileLight: _f2EnML, mobileDark: _f2EnMD },
    ru: { desktopLight: _f2RuDL, desktopDark: _f2RuDD, mobileLight: _f2RuML, mobileDark: _f2RuMD },
  },
  "04-policy-state-machine": {
    en: { desktopLight: _f3EnDL, desktopDark: _f3EnDD, mobileLight: _f3EnML, mobileDark: _f3EnMD },
    ru: { desktopLight: _f3RuDL, desktopDark: _f3RuDD, mobileLight: _f3RuML, mobileDark: _f3RuMD },
  },
  "03-layer-map": {
    en: { desktopLight: _f4EnDL, desktopDark: _f4EnDD, mobileLight: _f4EnML, mobileDark: _f4EnMD },
    ru: { desktopLight: _f4RuDL, desktopDark: _f4RuDD, mobileLight: _f4RuML, mobileDark: _f4RuMD },
  },
};
