// Auto-generated by havamal's sync_to_blog.py. Do not edit by
// hand — edits will be clobbered on the next sync.

import type { ImageMetadata } from "astro";

import _f1EnDL from "./01-rag-failure-layers.en.light.png";
import _f1EnDD from "./01-rag-failure-layers.en.dark.png";
import _f1EnML from "./01-rag-failure-layers.mobile.en.light.png";
import _f1EnMD from "./01-rag-failure-layers.mobile.en.dark.png";
import _f1RuDL from "./01-rag-failure-layers.ru.light.png";
import _f1RuDD from "./01-rag-failure-layers.ru.dark.png";
import _f1RuML from "./01-rag-failure-layers.mobile.ru.light.png";
import _f1RuMD from "./01-rag-failure-layers.mobile.ru.dark.png";

import _f2EnDL from "./02-wiki-three-layers.en.light.png";
import _f2EnDD from "./02-wiki-three-layers.en.dark.png";
import _f2EnML from "./02-wiki-three-layers.mobile.en.light.png";
import _f2EnMD from "./02-wiki-three-layers.mobile.en.dark.png";
import _f2RuDL from "./02-wiki-three-layers.ru.light.png";
import _f2RuDD from "./02-wiki-three-layers.ru.dark.png";
import _f2RuML from "./02-wiki-three-layers.mobile.ru.light.png";
import _f2RuMD from "./02-wiki-three-layers.mobile.ru.dark.png";

import _f3EnDL from "./03-compute-shift-quadrant.en.light.png";
import _f3EnDD from "./03-compute-shift-quadrant.en.dark.png";
import _f3EnML from "./03-compute-shift-quadrant.mobile.en.light.png";
import _f3EnMD from "./03-compute-shift-quadrant.mobile.en.dark.png";
import _f3RuDL from "./03-compute-shift-quadrant.ru.light.png";
import _f3RuDD from "./03-compute-shift-quadrant.ru.dark.png";
import _f3RuML from "./03-compute-shift-quadrant.mobile.ru.light.png";
import _f3RuMD from "./03-compute-shift-quadrant.mobile.ru.dark.png";

export interface FigureVariants {
  desktopLight: ImageMetadata;
  desktopDark: ImageMetadata;
  mobileLight: ImageMetadata;
  mobileDark: ImageMetadata;
}

export type FigureSet = Record<"en" | "ru", FigureVariants>;

export const figures: Record<string, FigureSet> = {
  "01-rag-failure-layers": {
    en: { desktopLight: _f1EnDL, desktopDark: _f1EnDD, mobileLight: _f1EnML, mobileDark: _f1EnMD },
    ru: { desktopLight: _f1RuDL, desktopDark: _f1RuDD, mobileLight: _f1RuML, mobileDark: _f1RuMD },
  },
  "02-wiki-three-layers": {
    en: { desktopLight: _f2EnDL, desktopDark: _f2EnDD, mobileLight: _f2EnML, mobileDark: _f2EnMD },
    ru: { desktopLight: _f2RuDL, desktopDark: _f2RuDD, mobileLight: _f2RuML, mobileDark: _f2RuMD },
  },
  "03-compute-shift-quadrant": {
    en: { desktopLight: _f3EnDL, desktopDark: _f3EnDD, mobileLight: _f3EnML, mobileDark: _f3EnMD },
    ru: { desktopLight: _f3RuDL, desktopDark: _f3RuDD, mobileLight: _f3RuML, mobileDark: _f3RuMD },
  },
};
