// Auto-generated by havamal's sync_to_blog.py. Do not edit by hand —
// edits will be clobbered on the next sync. Imports are static so Astro
// can hook them into the astro:assets pipeline; import.meta.glob does
// not resolve when BlogFigure is rendered as a slotted child of a React
// island (Astro 6 limitation).

import type { ImageMetadata } from "astro";

import f1EnDL from "./01-rag-failure-layers.en.light.png";
import f1EnDD from "./01-rag-failure-layers.en.dark.png";
import f1EnML from "./01-rag-failure-layers.mobile.en.light.png";
import f1EnMD from "./01-rag-failure-layers.mobile.en.dark.png";
import f1RuDL from "./01-rag-failure-layers.ru.light.png";
import f1RuDD from "./01-rag-failure-layers.ru.dark.png";
import f1RuML from "./01-rag-failure-layers.mobile.ru.light.png";
import f1RuMD from "./01-rag-failure-layers.mobile.ru.dark.png";

import f2EnDL from "./02-wiki-three-layers.en.light.png";
import f2EnDD from "./02-wiki-three-layers.en.dark.png";
import f2EnML from "./02-wiki-three-layers.mobile.en.light.png";
import f2EnMD from "./02-wiki-three-layers.mobile.en.dark.png";
import f2RuDL from "./02-wiki-three-layers.ru.light.png";
import f2RuDD from "./02-wiki-three-layers.ru.dark.png";
import f2RuML from "./02-wiki-three-layers.mobile.ru.light.png";
import f2RuMD from "./02-wiki-three-layers.mobile.ru.dark.png";

import f3EnDL from "./03-compute-shift-quadrant.en.light.png";
import f3EnDD from "./03-compute-shift-quadrant.en.dark.png";
import f3EnML from "./03-compute-shift-quadrant.mobile.en.light.png";
import f3EnMD from "./03-compute-shift-quadrant.mobile.en.dark.png";
import f3RuDL from "./03-compute-shift-quadrant.ru.light.png";
import f3RuDD from "./03-compute-shift-quadrant.ru.dark.png";
import f3RuML from "./03-compute-shift-quadrant.mobile.ru.light.png";
import f3RuMD from "./03-compute-shift-quadrant.mobile.ru.dark.png";

export interface FigureVariants {
  desktopLight: ImageMetadata;
  desktopDark: ImageMetadata;
  mobileLight: ImageMetadata;
  mobileDark: ImageMetadata;
}

export type FigureSet = Record<"en" | "ru", FigureVariants>;

export const figures: Record<string, FigureSet> = {
  "01-rag-failure-layers": {
    en: { desktopLight: f1EnDL, desktopDark: f1EnDD, mobileLight: f1EnML, mobileDark: f1EnMD },
    ru: { desktopLight: f1RuDL, desktopDark: f1RuDD, mobileLight: f1RuML, mobileDark: f1RuMD },
  },
  "02-wiki-three-layers": {
    en: { desktopLight: f2EnDL, desktopDark: f2EnDD, mobileLight: f2EnML, mobileDark: f2EnMD },
    ru: { desktopLight: f2RuDL, desktopDark: f2RuDD, mobileLight: f2RuML, mobileDark: f2RuMD },
  },
  "03-compute-shift-quadrant": {
    en: { desktopLight: f3EnDL, desktopDark: f3EnDD, mobileLight: f3EnML, mobileDark: f3EnMD },
    ru: { desktopLight: f3RuDL, desktopDark: f3RuDD, mobileLight: f3RuML, mobileDark: f3RuMD },
  },
};
